version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smartrw_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - smartrw_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartrw_backend
    restart: unless-stopped
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm start"
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - smartrw_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartrw_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - smartrw_network

  nginx:
    image: nginx:alpine
    container_name: smartrw_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - smartrw_network

volumes:
  mysql_data:
  backend_uploads:

networks:
  smartrw_network:
    driver: bridge
